### PR TITLE
Change libdaque version to follow dub best practices

### PR DESCRIPTION
**Pull request by quevangel**

### CODE REVIEW

**Comment by quevangel** [comment]
As it was always told by dub, it is now not recommended/supported using branches as versions to fetch from dub. So we now will use numbered versions instead. This requires a change in dub.json and co.

**Comment by davidomarf** [comment]
Keep things apart. Approving the changes to stop using branch names to specify packages version isn't the same as approving the new file about coding standards.

Following that second point, should we remove CONTRIBUTING.md and CODE_OF_CONDUCT.md?

Issue and PR templates won't be removed nor included in daque-dev/coding-standards

**Review by davidomarf — CHANGES_REQUESTED** [review]
It would be nice to say where to find Daque's coding standard.

**Comment by davidomarf** [comment]
Well, actually I don't understand what coding-style.md is for.

**Comment by davidomarf** [comment]
Also, I think it will be easier for someone that finds our source code, to start contributing if it just follows an already standardized rule: having a CONTRIBUTING.md file.

I honestly think that making our rules spaguetti-like (like having a coding-style file that references a code-style-guide in another repository) will make anyone less interested in doing some contributions.

I think I see your point: that having multiple files with the same content in all our repositories may be a waste and may be redundant.

But it's standard, and I don't think that following the standard is un-original or lazy.

**Comment by quevangel** [comment]
The idea is not to make it spaghetti-like, rather to make it tree-like and hierarchical.

**Comment by quevangel** [comment]
I agree the two changes should be in different PR's.

**Comment by davidomarf** [comment]
> The idea is not to make it spaghetti-like, rather to make it tree-like and hierarchical.

I feel it will make it (them) less readable.

**Comment by davidomarf** [comment]
I renamed PR and deleted file related to coding standards. 

Changes are approved now, @quevangel will merge unless anything else needs discussion.

**Review by davidomarf — APPROVED** [review]

**Comment by davidomarf** [comment]
Sign unsigned commits.

**Comment by davidomarf** [comment]
THIS IS FORMALLY TREASON.

**Comment by quevangel** [comment]
**YOU WEREN'T THERE WHEN I NEEDED YOU THE MOST!**

**Comment by davidomarf** [comment]
- FBI, OPEN THE DOOR.

**Comment by quevangel** [comment]
> Leaves the room, in the background a white-on-black terminal showing 1520 unsigned commits being forcefully pushed to master.

**Comment by davidomarf** [comment]
> Googles "how to un-do changes in git repository from a certain commit"

> Googles "what to do if my company lost half its work force in just one day"

**Comment by davidomarf** [comment]
In a serious note. Next merge from develop to master will be the last one to ignore branch protection rules. 

Actually, lemme open an issue about merging immediately to refresh our spirits.

**Comment by quevangel** [comment]
I agree.

**Pull request merged**
